### ISSUE TITLE
radiant strategy broken

### ISSUE THREAD

**Issue by mcmasterg** [SymbiFlow/fpga-tool-perf#14]
Was known to not be working. I just observed some tcl error in the output complaining about wrong number arguments.

**Comment by JohnDMcMaster** [comment]
The issue was that "default" is not a valid strategy in the CLI tools, but rather a GUI abstraction. If you had set a strategy directly, it does work. In any case, 3271ef8c6761f8f08acd226680456e211b5adc7a removes "default" as a valid option, instead setting Timing as the default.

Some quick tests on picorv32 showed that Timing and Quick gave the same result, but Area did in fact give a smaller design.

mcmaster@phantom:~/sf/fpga-tool-perf$ python3 fpgaperf.py --toolchain radiant-synpro --project picorv32-wrap --device "up5k" --package "uwg30" --strategy Area
    Writing to build/ice40-up5k-uwg30_radiant-synpro_picorv32-wrap_carry-y_Area
    Running: /home/mcmaster/sf/fpga-tool-perf/radiant.sh --syn synplify --strategy Area
    Running: iceunpack my.bin my.asc
    Running: icetime -tmd up5k my.asc
    Design ice40-up5k-uwg30_radiant-synpro_picorv32-wrap_carry-y_Area
      Family: ice40
      Device: up5k
      Package: uwg30
      Project: picorv32-wrap
      Toolchain: radiant-synpro
      Strategy: Area
      Carry: True
      Seed: default
    Timing:
      nop:             0.001
      radiant.sh:      84.015
      iceunpack:       2.611
      bit-all:         86.627
      icetime:         7.101
    Max frequency: 17.380 MHz
    Resource utilization
      BRAM:                5
      CARRY:               370
      DFF:                 1121
      GLB:                 4
      IOB:                 3
      LUT:                 2293
      PLL:                 0
mcmaster@phantom:~/sf/fpga-tool-perf$ python3 fpgaperf.py --toolchain radiant-synpro --project picorv32-wrap --device "up5k" --package "uwg30" --strategy Quick
    Writing to build/ice40-up5k-uwg30_radiant-synpro_picorv32-wrap_carry-y_Quick
    Running: /home/mcmaster/sf/fpga-tool-perf/radiant.sh --syn synplify --strategy Quick
    Running: iceunpack my.bin my.asc
    Running: icetime -tmd up5k my.asc
    Design ice40-up5k-uwg30_radiant-synpro_picorv32-wrap_carry-y_Quick
      Family: ice40
      Device: up5k
      Package: uwg30
      Project: picorv32-wrap
      Toolchain: radiant-synpro
      Strategy: Quick
      Carry: True
      Seed: default
    Timing:
      nop:             0.001
      radiant.sh:      93.466
      iceunpack:       2.826
      bit-all:         96.293
      icetime:         7.350
    Max frequency: 19.250 MHz
    Resource utilization
      BRAM:                5
      CARRY:               403
      DFF:                 1137
      GLB:                 3
      IOB:                 3
      LUT:                 2427
      PLL:                 0
mcmaster@phantom:~/sf/fpga-tool-perf$ python3 fpgaperf.py --toolchain radiant-synpro --project picorv32-wrap --device "up5k" --package "uwg30" --strategy Timing
    Writing to build/ice40-up5k-uwg30_radiant-synpro_picorv32-wrap_carry-y_Timing
    Running: /home/mcmaster/sf/fpga-tool-perf/radiant.sh --syn synplify --strategy Timing
    Running: iceunpack my.bin my.asc
    Running: icetime -tmd up5k my.asc
    Design ice40-up5k-uwg30_radiant-synpro_picorv32-wrap_carry-y_Timing
      Family: ice40
      Device: up5k
      Package: uwg30
      Project: picorv32-wrap
      Toolchain: radiant-synpro
      Strategy: Timing
      Carry: True
      Seed: default
    Timing:
      nop:             0.001
      radiant.sh:      86.797
      iceunpack:       2.636
      bit-all:         89.434
      icetime:         7.192
    Max frequency: 19.250 MHz
    Resource utilization
      BRAM:                5
      CARRY:               403
      DFF:                 1137
      GLB:                 3
      IOB:                 3
      LUT:                 2427
      PLL:                 0
